# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

choose_best_neighbor <- function(boundary_tracts, emp_vec, unemp_vec, pop_vec, asu_emp, asu_unemp, asu_pop, ur_thresh = 0.0645) {
    .Call(`_ASUbuildR_choose_best_neighbor`, boundary_tracts, emp_vec, unemp_vec, pop_vec, asu_emp, asu_unemp, asu_pop, ur_thresh)
}

