# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_asu_edges <- function(nb, asu_vec) {
    .Call(`_ASUbuildR_build_asu_edges`, nb, asu_vec)
}

choose_best_drop_candidate <- function(drop_candidates, unemp_vec, emp_vec, remaining_unemp, remaining_emp, total_new_unemp, total_new_emp, unemp_buffer) {
    .Call(`_ASUbuildR_choose_best_drop_candidate`, drop_candidates, unemp_vec, emp_vec, remaining_unemp, remaining_emp, total_new_unemp, total_new_emp, unemp_buffer)
}

choose_best_neighbor <- function(boundary_tracts, emp_vec, unemp_vec, pop_vec, asu_emp, asu_unemp, asu_pop, ur_thresh = 0.0645) {
    .Call(`_ASUbuildR_choose_best_neighbor`, boundary_tracts, emp_vec, unemp_vec, pop_vec, asu_emp, asu_unemp, asu_pop, ur_thresh)
}

